### ISSUE TITLE
I might be doing something wrong, a little help?

### ISSUE THREAD

**Issue by maxacarvalho** [staudenmeir/belongs-to-through#103]
Hi, thanks for your nice package.
I think I'm doing something wrong, I can't make it work with my use case.

What I have is:

`nick_comunica_aws_sms_usage_reports`

| column   |
| ------------ |
| id            |
| notification_id (fk nick_comunica_notifications)   |

---

`nick_comunica_notifications`

| column   |
| ------------ |
| id            |
| client_id (fk clients)   |
| message  |

---

`clients`

| column   |
| ------------ |
| id            |
| name   |

---

So, an entry in the `nick_comunica_aws_sms_usage_reports` table belongs to an entry in the `nick_comunica_notifications` table which belongs to an entry in the `clients` table.

In my `AwsSmsUsageReport` model I added the trait `Znck\Eloquent\Traits\BelongsToThrough` and the following method:

```php

    public function client(): BelongsToThrough
    {
        return $this->belongsToThrough(
            related: Client::class,
            through: Notification::class,
        );
    }
```

Then I instantiate a record from the `AwsSmsUsageReport` model:

`$report = AwsSmsUsageReport::query()->find(15);`

When I call the `client` relationship I get a `null` response back.  
By inspecting the SQL query that's running I can see that the query misses the `notification_id` in the call to the `clients` table:

```sql
SELECT
  *
FROM
  `nick_comunica_aws_sms_usage_reports`
WHERE
  `nick_comunica_aws_sms_usage_reports`.`id` = 15
LIMIT
  1
```

```sql
SELECT
  `clients`.*
FROM
  `clients`
  INNER JOIN `nick_comunica_notifications` ON `nick_comunica_notifications`.`client_id` = `clients`.`id`
WHERE
  `nick_comunica_notifications`.`id` IS NULL
LIMIT
  1
```

Any help?

Thank you!

**Comment by staudenmeir** [comment]
Hi @maxacarvalho,

> When I call the client relationship I get a null response back

What does your code look like?

**Comment by maxacarvalho** [comment]
Hi @staudenmeir 
Thanks for your speedy reply. But I just realised that I can get it to work with the Laravel standard `hasOneThrough` and `hasManyThrough` relationships 🤦🏽 

Here's the solution:

`AwsSmsUsageReport` model:

```php

    public function client(): HasOneThrough
    {
        return $this->hasOneThrough(
            Client::class,
            Notification::class,
            'id',
            'id',
            'notification_id',
            'client_id'
        );
    }
```

`Client` model:

```php

    public function awsSmsUsageReports()
    {
        return $this->hasManyThrough(
            AwsSmsUsageReport::class,
            Notification::class,
        );
    }
```
