### ISSUE TITLE
belongsToThrough with custom foreign key issues

### ISSUE THREAD

**Issue by WillieOng-HK** [staudenmeir/belongs-to-through#108]
`Community` hasMany `Building` hasMany `Floor` hasMany `Flat`

table name
`commres_communities`
`commres_buildings`
`commres_floors`
`commres_flats`

foreign key
`commres_buildings.community_id`
`commres_floors.building_id`
`commres_flats.floor_id`

I want to define Floor belongsToThrough community, I tried the following code:
```
public function community()
    {
        return $this->belongsToThrough(
            Community::class, 
            Building::class, 
            foreignKeyLookup: [
                Building::class => 'community_id',
            ],
            localKeyLookup: [
                Building::class => 'id',
            ]
        );
    }
```

its prompt `Unknown column 'commres_buildings.commres_community_id' in 'on clause'`

**Comment by staudenmeir** [comment]
Hi @WillieOng-HK,

Try this relationship:

```php
public function community()
{
    return $this->belongsToThrough(
        Community::class, 
        Building::class, 
        foreignKeyLookup: [
            Community::class => 'community_id',
            Building::class => 'building_id',
        ]
    );
}
```
