### ISSUE TITLE
Hide laravel_through_key from json response

### ISSUE THREAD

**Issue by ankurk91** [staudenmeir/belongs-to-through#38]
Hi,

The key `laravel_through_key` is coming in json response, can we hide it?
We can utilize the [Eloquent Trait Initializers](https://github.com/laravel/framework/pull/24467)
For example:
```php
<?php 

trait BelongsToThrough
{

    public function initializeBelongsToThrough() {
          $this->hidden[] = 'laravel_through_key';
    }

}
```

**Comment by staudenmeir** [comment]
The package can't solve this: `$hidden` has to be set in the *related* model, but the `BelongsToThrough` trait is used in the *parent* model.

You'll have to put `protected $hidden = ['laravel_through_key'];` in your related model.

**Comment by ankurk91** [comment]
Got it, i am doing the same to fix this.
Thanks.
