### ISSUE TITLE
Entity hasOne IntermediateEntity belongsTo TargetEntity

### ISSUE THREAD

**Issue by ahtshamraziq** [staudenmeir/belongs-to-through#39]
`School` hasOne `Address`
`Address` belongsTo `City`

I want to define a relationship on `School` model that gives me the city it is located in.
The problem is, I have a `hasOne` instead of `belongsTo` relationship with the intermediate model.

```
class School extends Model
{
    public function address()
    {
        return $this->hasOne('App\Address');
    }

    public function city()
    {
        // What to do
    }
}
```

**Comment by staudenmeir** [comment]
You can use my other package for this: https://github.com/staudenmeir/eloquent-has-many-deep

```php
class School extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function city()
    {
        return $this->hasOneDeep(City::class, [Address::class], [null, 'id'], [null, 'city_id']);
    }
}
```

In Laravel 5.8, you can use `HasOneThrough`:

```php
class School extends Model
{
    public function city()
    {
        return $this->hasOneThrough(City::class, Address::class, null, 'id', null, 'city_id');
    }
}
```

**Comment by ahtshamraziq** [comment]
Thanks! Works like a charm. I'll devise the inverse myself as an exercise.
