### ISSUE TITLE
laravel nova get foreign key name

### ISSUE THREAD

**Issue by hengkydev** [staudenmeir/belongs-to-through#41]
Hei im use your package on laravel nova to use belongs to dependency field
https://github.com/orlyapps/nova-belongsto-depend

which is i need to get higher parent without adding more field in my table .
that package i mention above is using more fk field to get higher parent
then i tried to use your package to make it more efficient 

your package is worked perfectly when i use it with Tinker 

![image](https://user-images.githubusercontent.com/17931528/63577707-3a585580-c5b9-11e9-99c0-7f956edc443a.png)

but when i tried to use in Laravel nova or to combine with package above 
im getting this error
![image](https://user-images.githubusercontent.com/17931528/63577863-83100e80-c5b9-11e9-947e-939e40dfb0fd.png)

this error showing up when on index page and create page 

and btw nice works !

**Comment by nathanheffley** [comment]
Where is your code for the version of your package that's broken?

**Comment by hengkydev** [comment]
is default usage of your package i use latest version
this on city model

```php
 use \Znck\Eloquent\Traits\BelongsToThrough;

    protected $table    = 'city';
    protected $guarded  = ["id"];
    protected $fillable = [];

     /**
     * relation belongs through to country
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function country()
    {
        return $this->belongsToThrough('App\Models\Region\Country', 'App\Models\Region\State');
    }
```

**Comment by staudenmeir** [comment]
I'm afraid I won't be able to help you with this. I don't have Nova and can't test it.
