### ISSUE TITLE
hasMany to belongsTo

### ISSUE THREAD

**Issue by alasdairgallacher** [staudenmeir/belongs-to-through#48]
Hi

How would you go about this scenario:
`Business` → has many → `AttachedServices` → belongs to → `service`

Trying to use both of your packages, but struggling. 

Thanks!

**Comment by staudenmeir** [comment]
This looks like a native `BelongsToMany` relationship, have you tried that?
https://laravel.com/docs/7.x/eloquent-relationships#many-to-many

**Comment by alasdairgallacher** [comment]
That worked, thank you!

I was over complicating it I guess haha!
