### ISSUE TITLE
Any reason why this relationship didn't make it to the framework?

### ISSUE THREAD

**Issue by maelga** [staudenmeir/belongs-to-through#50]

**Comment by staudenmeir** [comment]
Laravel 5.8 added `HasOneThrough` that you can use to define `BelongsToThrough` relationships with a single intermediate model.

Deeper relationships are probably too much of an edge case.

**Comment by TKlie** [comment]
@staudenmeir Isn't a `HasOneThorugh` the opposite of the `BelongsToThrough`?

If we assume a table structure like
```
User
- id

Category
- id
- user_id

Item
- id
- category_id
```

With the relations
```php
class Category {
  public function user() {
    return $this->belongsTo(User::class);
  }
}

class Item {
  public function category() {
    return $this->belongsTo(Category::class);
  }
}
```

then I would assume I could retrieve an item's user using
```php
class Item {
  public function user() {
    return $this->belongsToThrough(User::class, Category::class);
  }
}
```

which `hasOneThrough` does not do. For `hasOneThrough` to work, the `User` would need to have one `category_id` instead of the `Category` having the `user_id` (unless I'm missing something - if it's possible, I'd be eager to know how!).

**Comment by staudenmeir** [comment]
By default, `HasOneThrough` is the opposite of `BelongsToThrough`, but you can achieve the same result by swapping foreign and local keys.

**Comment by Quendi6** [comment]
Hello, I have a problem, I always retrieve the right model, but with a key ID from the intermediate, I tried with hasOneThrough
```
class Shooting {
    public function customer() {
        return $this->belongsTo(
            'App\Customer',
        );
    }
    public function price() {
        return $this->hasOneThrough(
                    'App\Price',
                    'App\Customer',
                    'id', // Foreign key on customers table...
                    'id', // Foreign key on prices table...
                    'customer_id', // Local key on shootings table...
                    'price_id' // Local key on customers table...
                );
    }
}
```
And with your belongsToThrough Method 
```
class Shooting {
    public function customer() {
        return $this->belongsTo(
            'App\Customer',
        );
    }
    public function price() {
        return $this->belongsToThrough(
            'App\Price', 'App\Customer',
        );
    }
}

class Customer {
    public function price() {
        return $this->belongsTo(
            'App\Price',
        );
    }
}
```
Any idea ?

**Comment by staudenmeir** [comment]
@Quendi6 You are having this issue with both `hasOneThrough()` and `belongsToThrough()`, right?

**Comment by Quendi6** [comment]
Yes, exactly

**Comment by staudenmeir** [comment]
What versions of Laravel and the plugin are you using?

**Comment by Skintillion** [comment]
Having the same problem..

Meeting has many Question, which has many Answer

```
public function meeting() {
    return $this->hasOneThrough('Meeting','Question','id','id','question_id','meeting_id');
}

```

or

```
public function meeting() {
    return $this->belongsToThrough('Meeting','Question');
}
```

in both instances, the result Meeting model will have the ID of the intermediate Question model.
