### ISSUE TITLE
withTrashed doesn't work for destination model

### ISSUE THREAD

**Issue by ggolda** [staudenmeir/belongs-to-through#51]
In my model I have relation like that:
```php
return $this->belongsToThrough(
    Project::class,
    Asset::class
)->withTrashed();
```
But `withTrashed` doesn't work with `Project` model that has a `SoftDeletes` trait. As I can see from a query log, `deleted_at is null` is still added to a query.

**Comment by staudenmeir** [comment]
Please share the executed SQL.

**Comment by ggolda** [comment]
So for example above, both `Project` and `Asset` can be soft deleted. If I provide `withTrashed` with default values, here is the generated SQL query:
```sql
select `projects`.* from `projects` inner join `assets` on `assets`.`project_id` = `projects`.`id` where `assets`.`deleted_at` is null and `assets`.`id` = ? limit 1
```

If I specify a parameter for `withTrashed` call, the code looks like:
```php
return $this->belongsToThrough(
        Project::class,
        Asset::class
)->withTrashed('assets.deleted_at')
```
and SQL query:
```sql
select `projects`.* from `projects` inner join `assets` on `assets`.`project_id` = `projects`.`id` where `assets`.`id` = ? and `projects`.`deleted_at` is null limit 1
```

If I provide both `assets` and `projects` parameters to a `withTrashed` function call like that:
```php
return $this->belongsToThrough(
        Project::class,
        Asset::class
)->withTrashed(['assets.deleted_at', 'projects.deleted_at']);
```
query looks identical to a version where only assets parameter is specified:
```sql
select `projects`.* from `projects` inner join `assets` on `assets`.`project_id` = `projects`.`id` where `assets`.`id` = ? and `projects`.`deleted_at` is null limit 1
```

**Comment by staudenmeir** [comment]
You need two `withTrashed()` calls:

```php
return $is->belongsToThrough(
        Project::class,
        Asset::class
)->withTrashed()->withTrashed('assets.deleted_at');
```

`->withTrashed()` is the native Laravel call for the related model (`Project`); `->withTrashed('assets.deleted_at')` is the package's call for intermediate tables (`Asset`).

**Comment by ggolda** [comment]
Thanks, I will try it out!
