### ISSUE TITLE
Can't install on PHP 8

### ISSUE THREAD

**Issue by raphaelbeckmann** [staudenmeir/belongs-to-through#53]
It's not possible to use this on Laravel 6 and PHP 8.
Laravel requires `illuminate/database` @ "self.version" which means they're using 6.x on Laravel 6.x:
https://github.com/laravel/framework/blob/006ba38124df6a8a651546a0301d604665b394b7/composer.json#L56

However this package requires `illuminate/database` version 8.

Steps to reproduce:

```
$ composer create-project laravel/laravel:"^6.20" example-app
$ cd example-app
$ composer require staudenmeir/belongs-to-through:"^2.11.1"

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires staudenmeir/belongs-to-through ^2.11.1 -> satisfiable by staudenmeir/belongs-to-through[v2.11.1].
    - staudenmeir/belongs-to-through v2.11.1 requires illuminate/database ^8.0 -> found illuminate/database[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Solution:

This package should require `"illuminate/database": "^6.0|^7.0|^8.0"`.

**Comment by staudenmeir** [comment]
The package does support that: `composer require staudenmeir/belongs-to-through:"^2.9"`

**Comment by raphaelbeckmann** [comment]
Thank you, that worked.
