### ISSUE TITLE
ID of result is the ID of the intermediate table instead

### ISSUE THREAD

**Issue by Skintillion** [staudenmeir/belongs-to-through#54]
Meeting has many Question, which has many Answer

```
public function meeting() {
    return $this->hasOneThrough('Meeting','Question','id','id','question_id','meeting_id');
}

```

or

```
public function meeting() {
    return $this->belongsToThrough('Meeting','Question');
}
```

in both instances, the result Meeting model will have the ID of the intermediate Question model.

Laravel 6 and I installed your plugin ^2.5

**Comment by staudenmeir** [comment]
Can you log the executed queries when you load the `BelongsToThrough` relationship?
