### ISSUE TITLE
belongsTo > HasMany > belongsTo

### ISSUE THREAD

**Issue by h888t** [staudenmeir/belongs-to-through#55]
Hello! 

I may be overcomplicating this, but some advice would be appreciated :-)

I have the following

ModelA -> belongsTo -> ModelB -> belongsTo ->modelC -> HasMany ->modelD -> belongsTo -> modelE

How could I define this?

I am trying to inverse the following 

        return $this->hasManyDeepFromRelations($this->modelDrelationshipfunction(), (new ModelD)->modelc(), (new ModelC)->modelB(), (new ModelB)->modelArelationship());

**Comment by staudenmeir** [comment]
You also need to use the `eloquent-has-many-deep` package for the reverse relationship.

Do you want the relationship to return a single result or all related models?
