### ISSUE TITLE
BelongsToMany -> BelongsToThrough

### ISSUE THREAD

**Issue by allestaire** [staudenmeir/belongs-to-through#58]
Is this posible to do?

```
User:
 - id
 - username
 
Posts:
 - id
 - user_id
 - comment_id

Comment:
 - id
 - review_id
 - message
 
 Review:
  - id
  - message
```

Can this be doeable on this package?

`User - belongsToManay -> Post - belongsTo -> Comment - BelongsTo -> Review`

**Comment by staudenmeir** [comment]
Do you want to get all the related reviews or only a single one?

**Comment by allestaire** [comment]
Ohh sorry for not emphasizing the expected result that I wanted.

I need to get all the reviews:
```
users: [
    review,
    review,
    review,
    review,
]
```

**Comment by staudenmeir** [comment]
This package only retrieves a single related model. Use https://github.com/staudenmeir/eloquent-has-many-deep instead.

> User - belongsToManay -> Post 

Is there actually a `post_user` pivot table? Your table schema looks like `User -> hasMany -> Post` instead.
