### ISSUE TITLE
requires illuminate/database ~5.0 -> found illuminate/database[v5.0.0, ..., 5.8.x-dev] - Laravel 8 error

### ISSUE THREAD

**Issue by WellingtonOstemberg** [staudenmeir/belongs-to-through#59]
Problem 1
    - Root composer.json requires staudenmeir/belongs-to-through 2.5 -> satisfiable by staudenmeir/belongs-to-through[v2.5].
    - staudenmeir/belongs-to-through v2.5 requires illuminate/database ~5.0 -> found illuminate/database[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by staudenmeir** [comment]
Are you using the exact installation command from the README? If so, try `composer require staudenmeir/belongs-to-through`.

**Comment by WellingtonOstemberg** [comment]
> Are you using the exact installation command from the README? If so, try `composer require staudenmeir/belongs-to-through`.

Wow, so fast on your answer? Thks!

I'm using this:
composer require staudenmeir/belongs-to-through:"^2.5"

**Comment by staudenmeir** [comment]
Does it work without the `:"^2.5"` at the end?

**Comment by WellingtonOstemberg** [comment]
no, can i try without it?

**Comment by staudenmeir** [comment]
Yes, with Laravel 8 the version isn't necessary.

**Comment by WellingtonOstemberg** [comment]
it worked!
Thanks for your excelent job with this lib
