### ISSUE TITLE
BelongsTo > HasOne Relationship

### ISSUE THREAD

**Issue by jvbalcita** [staudenmeir/belongs-to-through#60]
Hi just wanted to ask if there's a way to connect belongsTo > HasOne relationship using the BelongsToThrought Trait.

I have a Admission Request > BelongsTo > Course > HasOne > PaymentTypes

Thank you for your answer! :)

**Comment by staudenmeir** [comment]
Please share the structure of all three tables.

**Comment by jvbalcita** [comment]
Hi @staudenmeir ,

Course
id

Admission Request
course_id

Payment Type
course_id

Admission Request > ``BelongsTo`` > Course > ``HasOne`` > PaymentTypes

**Comment by staudenmeir** [comment]
You can actually do this with a native `HasOneThrough`relationship:

```php
public function paymentTypes()
{
    return $this->hasOneThrough(
        PaymentType::class,
        Course::class,
        'id',
        'course_id',
        'course_id',
        'id'
    );
}
```

**Comment by jvbalcita** [comment]
This worked thank you @staudenmeir
