### ISSUE TITLE
Missing column on query... scratching head!

### ISSUE THREAD

**Issue by sparxooo** [staudenmeir/belongs-to-through#61]
Hi!

Have been trying to get this to work in my project. 

A user can be assigned jobs (pivot table), each job has many areas, which can have many locations, and then once a job in a location is finished a completed model (with location_id) is created.

Initially I was storing user_id, location_id, area_id and job_id into the Completed table, however this was affecting seeding - then I found your project! Now just storing user_id and location_id

I've tried to get the amount of completed locations: `$user->jobs()->withCount('completed')`, however just get this error message:
~~~sql
SQLSTATE[42S22]: COLUMN NOT FOUND: 1054 unknown COLUMN 'locations.job_id' IN 'where clause' (SQL:
SELECT     `jobs`.*,
           (
                      SELECT     count(*)
                      FROM       `completeds`
                      INNER JOIN `locations`
                      ON         `locations`.`id` = `completeds`.`location_id`
                      WHERE      `jobs`.`id` = `locations`.`job_id`
                      AND        `completeds`.`deleted_at` IS NULL) AS `completeds_count`,
           `job_subs`.`user_id`                                     AS `pivot_user_id`,
           `job_subs`.`job_id`                                      AS `pivot_job_id`,
           `job_subs`.`created_at`                                  AS `pivot_created_at`,
           `job_subs`.`updated_at`                                  AS `pivot_updated_at`
FROM       `jobs`
INNER JOIN `job_subs`
ON         `jobs`.`id` = `job_subs`.`job_id`
WHERE      `job_subs`.`user_id` = 1
AND        `jobs`.`deleted_at` IS NULL)
~~~

I have all the belongsToThrough relations in place in the intermediate models, but it still looks for the _id field (which doesn't exist).

Any ideas? Am I just doing it wrong?

**Comment by staudenmeir** [comment]
Please share the `jobs` relationship and the `Job` model.

**Comment by sparxooo** [comment]
`$user->jobs

        return $this->belongsToMany(Challenge::class, 'challenge_subs')->withTimestamps();

**Comment by sparxooo** [comment]
I will get that to you once I'm back at the computer!

**Comment by sparxooo** [comment]
Hi staudenmeir,

Job Model: `<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use \Znck\Eloquent\Traits\BelongsToThrough;

class Job extends Model
{
    use HasFactory, SoftDeletes, BelongsToThrough;

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function areas()
    {
        return $this->hasMany(Area::class);
    }

    public function locations()
    {
        return $this->hasManyThrough(Location::class, Area::class);
    }

    public function completeds()
    {
        return $this->hasManyThrough(Completed::class, Location::class);
    }

    public function subscribed()
    {
        return $this->belongsToMany(User::class, 'job_subs')->withTimestamps();
    }
}
`

User model "jobs" relationship:

`public function jobs()
    {
        return $this->belongsToMany(Job::class, 'job_subs')->withTimestamps();
    }`

**Comment by staudenmeir** [comment]
> I have all the belongsToThrough relations in place

What do these relationships look like and how are they involved in your query?

**Comment by sparxooo** [comment]
And i've managed to fix it, but not totally sure how!

I noticed that some of my relations on my User model were incorrect - using hasManyThrough when in fact they should have been hasMany. 

Thanks for a great project! :)
