### ISSUE TITLE
Column not found: 1054

### ISSUE THREAD

**Issue by rossco555** [staudenmeir/belongs-to-through#66]
Firstly, thanks for the package - it's just what I needed. Secondly, I'm a novice so my apologies in advance if I'm just doing something dumb here but I think this may be an issue.

I have a `Hazard` model that relates to the `Project` model as follows:

```
public function project()
    {
        // relies on belongsToThrough package (https://github.com/staudenmeir/belongs-to-through)
        return $this->belongsToThrough(Project::class, Node::class);
    }
```

To confirm:
- [x] The nodes table relates to the projects table

```
Schema::table('nodes', function (Blueprint $table) {
            $table->unsignedBigInteger('project_id');
            $table->foreign('project_id', 'project_fk_2244664')->references('id')->on('projects');
        });
```

- [x] The hazards table relates to the nodes table

```
Schema::table('hazards', function (Blueprint $table) {
            $table->unsignedBigInteger('node_id');
            $table->foreign('node_id', 'node_fk_2244867')->references('id')->on('nodes');
        });
``` 

I have no doubt this works and if I query, for example, `Hazard::with(['project'])` then I get the expected relationship.

But there are two places where I have encountered issues:

1. When I query as below (this is in a filter class):

```
return $this->builder->whereHas('project', function($qry) use ($value) {
info($qry->first());
            $qry->where('projects.id', $value);
                });
```

2. When I try to use the relationship in an accessor:

```
    protected function code(): Attribute
    {
        return new Attribute(
            get: fn () => $this->project->code . "-" . sprintf('%04d', $this->id),
        );
    }
```

In both instance I think I get the same underlying issue:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hazards.node_id' in 'where clause' (SQL: select * from `projects` inner join `nodes` on `nodes`.`project_id` = `projects`.`id` where `nodes`.`id` = `hazards`.`node_id` and `projects`.`deleted_at` is null and `is_active` = 1 limit 1)
```

This has me beat because I understand all those columns exist (and can see them there in the database). Could you please take a look?

**Comment by staudenmeir** [comment]
> I have no doubt this works and if I query, for example, Hazard::with(['project']) then I get the expected relationship.

What queries does `Hazard::with(['project'])->get()` execute?

> 1. When I query as below (this is in a filter class):

What happens when you remove `info($qry->first());`?

> 2. When I try to use the relationship in an accessor:

How are you using the accessor?

**Comment by rossco555** [comment]
Thanks for your response.

1. `return \App\Models\Hazard::with(['project'])->toSql();` yields `select * from `hazards` where `hazards`.`deleted_at` is null` which obviously isn't as expected. The project() relationship is as specified in the original.

2. Removing `info($qry->first());` this (and I can see now that this debug step would cause another issue!) the query appears to be as follows, **but the actual results are unfiltered**:

```
select * from `hazards` where (exists (select * from `projects` inner join `nodes` on `nodes`.`project_id` = `projects`.`id` where `nodes`.`id` = `hazards`.`node_id` and `projects`.`id` = '7' and `nodes`.`deleted_at` is null and `nodes`.`deleted_at` is null and `projects`.`deleted_at` is null and `is_active` = 1) and `description` like '%%' or `element` like '%%') and `hazards`.`deleted_at` is null limit 10 offset 0
```

Not sure if this helps?

**Comment by staudenmeir** [comment]
> 1. return \App\Models\Hazard::with(['project'])->toSql(); yields select * from hazardswherehazards.deleted_at is null which obviously isn't as expected. The project() relationship is as specified in the original.

That's actually correct because there's a separate eager loading query that you prevent from being executed. Use this instead:

```php
\DB::enableQueryLog();

Hazard::with(['project'])->get();

dd(\DB::getQueryLog());
```

> 2. Removing info($qry->first()); this (and I can see now that this debug step would cause another issue!) the query appears to be as follows, but the actual results are unfiltered:

Please provide a [fiddle](http://sqlfiddle.com/) with sample data that shows how this query returns a incorrect result.

**Comment by rossco555** [comment]
With `\DB::enableQueryLog(); ...` I get the following. This isn't a problem and the project relationship comes through as expected.

```
select `projects`.*, `nodes`.`id` as `laravel_through_key` from `projects` inner join `nodes` on `nodes`.`project_id` = `projects`.`id` where `nodes`.`deleted_at` is null and `nodes`.`id` in (?, ?, ?, ?, …, ?, ?, ?) and `projects`.`deleted_at` is null and `is_active` = ?
```

Extending that then so the encased query is `$hazards = Hazard::with(['project'])->filter($filter);` I again get similar:

```
select `projects`.*, `nodes`.`id` as `laravel_through_key` from `projects` inner join `nodes` on `nodes`.`project_id` = `projects`.`id` where `nodes`.`deleted_at` is null and `nodes`.`id` in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) and `projects`.`deleted_at` is null and `is_active` = ?
```

...however that is with my class `public function project_id(string $value = null): Builder` completely commented out and skipped. Reinstating that to:

```
public function project_id(string $value = null): Builder
    {
        return $this->builder->whereHas('project', function($qry) use ($value) {
                    $qry->where('projects.id', $value);
            });
    }
```

...gives:

```
select `projects`.*, `nodes`.`id` as `laravel_through_key` from `projects` inner join `nodes` on `nodes`.`project_id` = `projects`.`id` where `nodes`.`deleted_at` is null and `nodes`.`id` in (?) and `projects`.`deleted_at` is null and `is_active` = ?
```

I'm not sure whether my mistakes breaking into queries trying to debug has contributed to the first issue, but that is now resolved when I remove all debug code. That is, the relationship to project works and is filtered correctly (original item #1 resolved) and I also get a valid `code` from the accessor I described in item #2.

Where the accessor still doesn't work is when I attempt to load `Actions`. These have a hasManyDeep relationship as follows and the error is `Attempt to read property "code" on null` and comes from the `Hazard` model class, and specifically the `code()` accessor.

```
public function project()
    {
        // relies on HasRelationships package (https://github.com/staudenmeir/eloquent-has-many-deep)
        return $this->hasManyDeepFromRelations($this->nodes(), (new Node)->project());
    }
```

I'm still trying to work out how I can create a fiddle to give you anything meaningful - I've not used it before - will come back to you with that.

Thanks for your patience in understanding this.

**Comment by rossco555** [comment]
I may have addressed this by changing the accessor as follows:

```
protected function code(): Attribute
    {
        return new Attribute(
            get: fn () => $this->project['code'] . "-" . sprintf('%04d', $this->id),
        );
    }
```

ie, accessing code as an array element rather than a collection property.

Apologies for wasting your time with all of this!

**Comment by staudenmeir** [comment]
So everything is working now?

> I'm not sure whether my mistakes breaking into queries trying to debug has contributed to the first issue, but that is now resolved when I remove all debug code.

`info($qry->first());` executes the subquery and thereby tampers with the query you are debugging.

**Comment by rossco555** [comment]
Thank you, yes I think it is. I've still got some things to work through on
my end but I think in addition to what I already described there is a
global "Is Active" scope you can see in the query and my test seed data was
not accurate enough so I may have been trying to get the project
relationship for a hazard when the project had been deactivated.

Really sorry to have used up your time, and I do appreciate it and your
work on this package. Thank you!
