### ISSUE TITLE
 staudenmeir/belongs-to-through v2.5 requires illuminate/database ~5.0

### ISSUE THREAD

**Issue by chibyk101** [staudenmeir/belongs-to-through#72]
Trying to install in laravel 9.x composer throws an error of dependency conflict.

error thrown:

Problem 1
    - Root composer.json requires staudenmeir/belongs-to-through 2.5 -> satisfiable by staudenmeir/belongs-to-through[v2.5].
    - staudenmeir/belongs-to-through v2.5 requires illuminate/database ~5.0 -> found illuminate/database[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because 
it conflicts with another require.

**Comment by staudenmeir** [comment]
Hi @chibyk101,
Please try installing the package with `composer require staudenmeir/belongs-to-through` instead.

**Comment by chibyk101** [comment]
> Hi @chibyk101, Please try installing the package with `composer require staudenmeir/belongs-to-through` instead.

Thank you. it worked
