### ISSUE TITLE
unable to install package 

### ISSUE THREAD

**Issue by ahmad-mujamil** [staudenmeir/belongs-to-through#75]
` - Root composer.json requires staudenmeir/belongs-to-through ^2.13 -> satisfiable by staudenmeir/belongs-to-through[v2.13].
    - staudenmeir/belongs-to-through v2.13 requires illuminate/database ^10.0 -> found illuminate/database[10.x-dev] but it conflicts with another require.`

please help

**Comment by staudenmeir** [comment]
Hi @ahmad-mujamil,
Is that the whole error message? Can you share your `composer.json` file?

**Comment by msulaimanmisri** [comment]
The same goes for me @staudenmeir. Here's my composer.json

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0",
        "cviebrock/eloquent-sluggable": "^9.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "jomweb/billplz-laravel": "^3.0",
        "laravel/breeze": "^1.7",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.14",
        "laravel/tinker": "^2.5",
        "realrashid/sweet-alert": "^5.1",
        "santigarcor/laratrust": "^7.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.0",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by staudenmeir** [comment]
@msulaimanmisri Did you use the exact command from the [README](https://github.com/staudenmeir/belongs-to-through#installation)?

**Comment by msulaimanmisri** [comment]
Yep sure @staudenmeir , I also tried to install using another version such as 2.9 & 2.10. I have also failed.

But the error is not the same if I run `composer require staudenmeir/belongs-to-through:"^2.5"`

2.9 and 2.10 show errors `PHP Version incompatible`,. I'm using PHP version 8.1.2.

**Comment by staudenmeir** [comment]
Please try `composer require staudenmeir/belongs-to-through:"^2.12"`.

**Comment by msulaimanmisri** [comment]
Yeah. It's work if I run `composer require staudenmeir/belongs-to-through:"^2.12"`.

Also tested my logic using what the instruction mentioned in [README](https://github.com/staudenmeir/belongs-to-through#readme).

**Comment by staudenmeir** [comment]
What operating system and terminal are you using?

**Comment by msulaimanmisri** [comment]
I'm using `Windows 10` and the terminal is coming from `VSCode version 1.74.3`

**Comment by msulaimanmisri** [comment]
Just to let you know @staudenmeir , I also ran `composer require staudenmeir/belongs-to-through:"^^^^2.5"` before this and still the error appears.

**Comment by staudenmeir** [comment]
Thanks. What does your `composer.json` look like now?

**Comment by msulaimanmisri** [comment]
Here's my `composer.json` look right now :

```
"require": {
        "php": "^8.0",
        "staudenmeir/belongs-to-through": "2.12"
    }
```

**Comment by staudenmeir** [comment]
It should be `"staudenmeir/belongs-to-through": "^2.12"` so you get all the updates.

What does `composer update staudenmeir/belongs-to-through:"^^^^2.12"`? give you?

**Comment by ahmad-mujamil** [comment]
> har

yes that the only error i get..
this my composer.json

`    "require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/fortify": "^1.16",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7",
        "livewire/livewire": "^2.10",
        "predis/predis": "^2.0",
        "rappasoft/laravel-authentication-log": "^2.0",
        "realrashid/sweet-alert": "^5.1",
        "spatie/laravel-permission": "^5.7",
        "torann/geoip": "^3.0",
        "yajra/laravel-datatables-oracle": "^10.2"`

**Comment by ahmad-mujamil** [comment]
Hi @staudenmeir 
it solve using `"staudenmeir/belongs-to-through": "^2.12"` this version

thanks ..
