### ISSUE TITLE
BelongsToThrough when the model to recover is polymorphic (morphTo)

### ISSUE THREAD

**Issue by joslingax** [staudenmeir/belongs-to-through#77]
Hi,

How can i recover C or D with belongsToThrough when i have to deal with a polymorphic relation
A → belongs to → B→ belongs to → C or D

     in A
    public function declarant()
    {
        return $this->belongsTo('\Modules\Declarants\Models\Declarant', 'declarant_id', 'id');
    }

    in B
    public function declarantable()
    {
        return $this->morphTo('declarantable', 'declarantable_type', 'declarantable_id');
    }

declarantable_id can belong to C or D

**Comment by joslingax** [comment]
![Example](https://user-images.githubusercontent.com/7707937/221420837-ac77d97f-db34-454e-b298-33092d3bc0a2.png)

**Comment by joslingax** [comment]
i d like to retrieve C or D from A with belongsToThrough knowing B has a polymorphic relation 
like this
public function declarantable()
{
    return $this->morphTo('declarantable', 'declarantable_type', 'declarantable_id');
}

**Comment by staudenmeir** [comment]
Hi @joslingax,
This is a bit more complicated, but you can achieve it with one of my other packages:
https://github.com/staudenmeir/laravel-merged-relations

1. Define the relationships:

```php
class A extends Model
{
    use \Staudenmeir\LaravelMergedRelations\Eloquent\HasMergedRelationships;

    public function declarantables()
    {
        return $this->mergedRelation('declarantables', 'b_id');
    }

    public function cs()
    {
        return $this->morphedByMany(C::class, 'declarantable', 'b_s', 'id', null, 'b_id');
    }

    public function ds()
    {
        return $this->morphedByMany(D::class, 'declarantable', 'b_s', 'id', null, 'b_id');
    }
}
```

2. Create the merge view in a migration:

```php
use Staudenmeir\LaravelMergedRelations\Facades\Schema;

Schema::createOrReplaceMergeView(
    'declarantables',
    [(new A())->cs(), (new A())->ds()]
);
```

`declarantables()` always returns a collection, so you need to take the first item:

```php
$declarantable = $a->declarantables()->first(); 
```
