### ISSUE TITLE
Cant change trough class id

### ISSUE THREAD

**Issue by arturasfrontit** [staudenmeir/belongs-to-through#82]
where is no way to change e_order_id

`select `e_orders`.* from `e_orders` inner join `e_order_items` on `e_order_items`.`e_order_id` = `e_orders`.`id` where `e_order_items`.`id` is null limit 1`

```
    public function order()
    {
        return $this->belongsToThrough(Order::class, OrderItem::class, 'invoice_id', null, [OrderItem::class=> 'order_id']);
    }
```

**Comment by staudenmeir** [comment]
Hi @arturasfrontit,
Try this instead:

```php
public function order()
{
    return $this->belongsToThrough(Order::class, OrderItem::class, 'invoice_id', null, [Order::class=> 'order_id']);
}                                                                                       ^^^^^
```

**Comment by arturasfrontit** [comment]
> Hi @arturasfrontit, Try this instead:
> 
> ```
> public function order()
> {
>     return $this->belongsToThrough(Order::class, OrderItem::class, 'invoice_id', null, [Order::class=> 'order_id']);
> }                                                                                       ^^^^^
> ```

Tried this one, but it didin't work for me

**Comment by staudenmeir** [comment]
What isn't working? Is there an error? What does the executed SQL look like?
