### ISSUE TITLE
table alias:( `alias`.`id` is null) appends to SQL WHERE clause.

### ISSUE THREAD

**Issue by zibafar** [staudenmeir/belongs-to-through#83]
Hi,
My  relationship path contains the same model multiple times, I use  specify a table alias
```

 public function referrer()
    {
        //Subscription → belongs to → User → belongs to → refer
        return $this->belongsToThrough(
            User::class,
            User::class . ' as alias',
            null,
            '',
            [ User::class => 'refer_id'  ]
        )->withoutGlobalScopes();
    }

```
the query result is :

```
select *
from `users`
    inner join `users` as `alias`
        on `alias`.`refer_id` = `users`.`id`
where `alias`.`id` is null
```
Obviously, the value (`alias`.`id` is null)  is always false and always **No records** will ever be found !
I can not understand why this destructive condition appends to SQL where  clause !

please help.

**Comment by zibafar** [comment]
`where `alias`.`id` is null` is removed form the query , 
when I comment this line :
` // $this->query->where($this->getQualifiedFirstLocalKeyName(), '=', $localValue);` in this file
[BelongsToThrough](https://github.com/staudenmeir/belongs-to-through/blob/master/src/Relations/BelongsToThrough.php) : Line 77
the malicious condition is removed
-----------------------

finally I solved this issue in this way:

```
 public function referrer()
    {
        //Subscription → belongs to → User → belongs to → refer
        return Relation::noConstraints(function (){
                return $this->belongsToThrough(
                    User::class,
                    User::class . ' as alias',
                    null,
                    '',
                    [ User::class => 'refer_id' ]
                )->withoutGlobalScopes();
        });

    }
```

**Comment by staudenmeir** [comment]
Hi @zibafar,
What does the `subscriptions` table look like? Can you share the migration?

**Comment by zibafar** [comment]
Thank you for your time

Subscriptions table:
```
Schema::create(Subscription::TBL, function (Blueprint $table) {

            $table->uuid('id')->primary();

            $table->uuid('user_id');
            $table->foreign('user_id')
                ->references('id')->on(User::TBL);

            $table->uuid('plan_id');
            $table->foreign('plan_id')
                ->references('id')->on(Plan::TBL);


            $table->uuid('group_id');
            $table->foreign('group_id')
                ->references('id')->on(BGroup::TBL);
           
           
            $table->date('starts_at')->nullable();
            $table->date('expires_at')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
```
Users table:
```

Schema::create(User::TBL, function (Blueprint $table) {
            $table->uuid('id')->primary();

            $table->uuid('refer_id')->nullable(); //hidden

            $table->timestamps();
            $table->softDeletes();
        });

```

**Comment by staudenmeir** [comment]
Unfortunately, the package doesn't support your combination of table alias and custom foreign key (`refer_id`). It looks for the `refer_id` attribute in the `Subscription` model that's what causes the `where alias.id is null` condition since the since the attribute doesn't exist.

You can use one of my other packages instead: https://github.com/staudenmeir/eloquent-has-many-deep

```php
class Subscription extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function referrer()
    {
        return $this->hasOneDeep(
            User::class,
            [User::class . ' as alias'],
            ['id', 'id'],
            ['user_id', 'refer_id']
        )->withoutGlobalScopes();
    }
}
```

**Comment by zibafar** [comment]
Thanks a lot, @staudenmeir 

your code works correctly.
note: we should use this trait to User model: 
`use \Staudenmeir\EloquentHasManyDeep\HasTableAlias;`
