### ISSUE TITLE
BelongsTo > BelongsTo

### ISSUE THREAD

**Issue by plakhin** [staudenmeir/belongs-to-through#87]
I have this table structure:

```
owners
 - id

cars
  - id
  - owner_id

keys
  - id
  - car_id
```

I already have these relationships set:

1. Owner > `HasOne` > Car > `HasOne` > Key
1. Key > `BelongsTo` > Car > `BelongsTo` -> Owner
1. Owner -> `HasOneThrough` > Key

How can I set [ Key > `???` -> Owner ] relationship?
Was trying to set [ Key > `BelongsToTrough` > Owner ] but with no luck.

Will highly appreciate your help 🙏

**Comment by staudenmeir** [comment]
Hi @plakhin,
Use this relationship:

```php
class Key extends Model
{
    use \Znck\Eloquent\Traits\BelongsToThrough;

    public function owner()
    {
        return $this->belongsToThrough(Owner::class, Car::class);
    }
}
```

**Comment by plakhin** [comment]
Thank you!
