### ISSUE TITLE
BelongsToThrough a polymorphic relationship?

### ISSUE THREAD

**Issue by nadirabbas** [staudenmeir/belongs-to-through#93]
Awesome package @staudenmeir! I need a little help if it is not too much to ask 
I have the following db schema:

![image](https://github.com/staudenmeir/belongs-to-through/assets/38838675/c504c165-01c3-4d94-9910-0d4f5b5a7212)

I want to be able to retrieve the customer on the Task model, which is either directly related to the task, or related through a device, or related through an attachment->device. How can I achieve this using BelongsToThrough package?

**Comment by staudenmeir** [comment]
Hi @nadirabbas,
It's not possible to define this kind of relationship with the package and I don't see any other way to do that either.

**Comment by nadirabbas** [comment]
@staudenmeir This is working for me, but it does iterate through every record so there seems to be no point anyway. But I still needed to do it to enable customer search on the tasks page:

```php
public function customer()
    {
        if ($this->taskable_type === Customer::class) return $this->belongsTo(Customer::class, 'taskable_id');
        if ($this->taskable_type === Device::class) {
            return $this->belongsToThrough(Customer::class, Device::class, foreignKeyLookup: [
                Device::class => 'taskable_id'
            ]);
        }
        return $this->belongsToThrough(Customer::class, [Device::class, Replaceable::class], foreignKeyLookup: [
            Replaceable::class => 'taskable_id'
        ]);
    }
```

**Comment by staudenmeir** [comment]
Yeah, you can get the customer for a single task with such a "dynamic" relationship, but there is no solution for eager loading etc.
